### ISSUE TITLE
Missing spritesheet

### ISSUE THREAD

**Issue by narwy** [sindreslungaard/ekalus#1]
Getting this error:
> Uncaught TypeError: Cannot read property 'textures' of undefined
From avatar.ts:
> sprites/avatars/${this.figure}/spritesheet.json

Missing from the folder?

**Comment by sindreslungaard** [comment]
Ah yes, the README should mention that [texturepacker](https://www.codeandweb.com/texturepacker) must be used to pack the sprites included in the repo. Including this file in your dist folder should solve it [sprites.zip](https://github.com/sindreslungaard/ekalus/files/2948841/sprites.zip)

**Comment by narwy** [comment]
Works 👍 

Engine looks good, looks really well coded + using PixiJS = bonus
